# Generated by Django 2.2.12 on 2020-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
